---
- name: Ensure postfix is installed
  package:
    name: postfix
    state: installed

- name: Ensure postfix is started and enabled at boot
  service:
    name: postfix
    state: started
    enabled: yes
