---
- name: Ensure dependencies are installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ zeyple_packages }}"

- name: Ensure application user exists
  user:
    name: zeyple
    shell: /bin/false
    home: /var/lib/zeyple/

- name: Ensure application folders exists
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode | default('') }}"
    owner: zeyple
    group: zeyple
  with_items:
    - path: /opt/zeyple
      state: directory
      mode: "0755"
    - path: /var/lib/zeyple/keys
      state: directory
      mode: "0700"

- name: Ensure application log file exists
  copy:
    content: ""
    dest: /var/log/zeyple.log
    force: no
    mode: "0744"
    owner: zeyple
    group: zeyple

- name: Download script
  get_url:
    url: "{{ item }}"
    dest: /opt/zeyple/
    mode: 0744
    owner: zeyple
    group: zeyple
  with_items:
    - https://raw.githubusercontent.com/infertux/zeyple/v{{ zeyple_version }}/zeyple/zeyple.py
    - https://raw.githubusercontent.com/infertux/zeyple/v{{ zeyple_version }}/selinux/zeyple.te
  register: application

- name: Ensure SELinux helper tools are installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ selinux_helper_tools }}"
  when: ansible_selinux.status is defined and ansible_selinux.status == "enabled"

- name: Check if SELinux module is already installed
  shell: "semodule -l | egrep '^zeyple'"
  ignore_errors: true
  changed_when: false
  register: semodule
  when: ansible_selinux.status is defined and ansible_selinux.status == "enabled"

- name: Remove SELinux module
  shell: "semodule -vr zeyple"
  when:
    - ansible_selinux.status is defined and ansible_selinux.status == "enabled"
    - application.changed
    - semodule.rc == 0

- name: Install SELinux module for application
  shell: "{{ item }}"
  args:
    chdir: /opt/zeyple/
  with_items:
    - "checkmodule -Mmo zeyple.mod zeyple.te"
    - "semodule_package -m zeyple.mod -o zeyple.pp"
    - "semodule -vi zeyple.pp"
  when: 
    - ansible_selinux.status is defined and ansible_selinux.status == "enabled"
    - application.changed or semodule.rc == 1

- name: Configure application
  get_url:
    url: https://raw.githubusercontent.com/infertux/zeyple/v{{ zeyple_version }}/zeyple/zeyple.conf.example
    dest: /etc/zeyple.conf
    force: no
    owner: zeyple
    group: zeyple

- name: Add zeyple filter to postfix
  blockinfile:
    path: /etc/postfix/master.cf
    marker: "# {mark} ZEYPLE FILTER"
    block: |
      zeyple    unix  -       n       n       -       -       pipe
        user=zeyple argv=/opt/zeyple/zeyple.py ${recipient}

      localhost:10026 inet  n       -       n       -       10      smtpd
        -o content_filter=
        -o receive_override_options=no_unknown_recipient_checks,no_header_body_checks,no_milters
        -o smtpd_helo_restrictions=
        -o smtpd_client_restrictions=
        -o smtpd_sender_restrictions=
        -o smtpd_recipient_restrictions=permit_mynetworks,reject
        -o mynetworks=127.0.0.0/8
        -o smtpd_authorized_xforward_hosts=127.0.0.0/8
  notify: restart postfix

- name: Ensure postfix uses zeyple filter
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^content_filter[ \t]*="
    line: "content_filter = zeyple"
  notify: restart postfix
