# -*- mode: ruby -*-
# vi: set ft=ruby :

system("rm -f ~/.ansible/roles/role_under_test && ln -s $(pwd)/../ ~/.ansible/roles/role_under_test")

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false
  config.vm.box = 'centos/7'

  servers = {
    "selfservice": "10.0.0.10",
  }

#  groups = {
#    "smtprelay1": ['smtprelay']
#  }
  
  servers.each do |server, ip|
    config.vm.define "#{server}" do |node|
      node.vm.hostname = "#{server}"
      node.vm.network 'private_network', ip: "#{ip}"
#      node.vm.network "forwarded_port", guest: 80, host: 8080
    end
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'test.yml'
#    ansible.groups = groups
  end

end
